# ************************  UPDATING PORT ******************************
server:
  port: 8082


#  *********************** DATA BASE CONFIGURATION *********************************
spring:
  application:
    name: RATING-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/ratingmicroservice?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: 3425
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  config:
    import: optional:configserver:http://localhost:8085



